// Printify color name to hex code mapping
// Fill in the hex values for each color
export const PRINTIFY_COLOR_MAP: Record<string, string> = {
  'Black': '#000000',
  'White': '#FFFFFF',
  'Navy': '',
  'Red': '',
  'Royal Blue': '',
  'Dark Grey': '',
  'Heather Grey': '',
  'Light Blue': '',
  'Pink': '',
  'Forest Green': '',
  'Maroon': '',
  'Purple': '',
  'Kelly Green': '',
  'Orange': '',
  'Yellow': '',
  'Tan': '',
  'Light Pink': '',
  'Brown': '',
  'Olive': '',
  'Turquoise': '#00afd7',
  'Lime': '',
  'Gold': '',
  'Silver': '',
  'Mint': '',
  'Coral': '',
  'Burgundy': '',
  'Charcoal': '',
  'Sky Blue': '',
  'Slate': '',
  'Cream': '',
  'Beige': '',
  'Heather Navy': '',
  'Heather Red': '',
  'Heather Blue': '',
  'Heather Green': '',
  'Heather Purple': '',
  'Athletic Heather': '',
  'Heather Forest': '#48655b',
  'Heather Cardinal': '#651d32',
  'Heather Royal': '',
  'Heather Grass Green': '#427c66',
  'Heather Orange': '',
  'Heather Yellow Gold': '#fdd26e',
  'Black Heather': '#454038',
  'Deep Heather': '',
  'Ash': '#f2f2f2',
  'Sport Grey': '',
  'True Royal': '',
  'Cardinal': '',
  'Kelly': '',
  'Heather Military Green': '',
  'Heather Midnight Navy': '',
  'Heather Stone': '',
  'Heather Deep Teal': '',
  'Heather Dusty Rose': '',
  'Heather Prism Peach': '',
  'Heather Mint': '',
  'Heather Team Purple': '',
  'Heather Columbia Blue': '',
  'Heather Mauve': '',
  'Heather True Royal': '#24509a',
  'Soft Cream': '',
  'Pebble': '',
  'Steel Blue': '',
  'Military Green': '',
  'Sunset': '',
  'Dusty Blue': '',
  'Mauve': '',
  'Ice Blue': '',
  'Heather Raspberry': '#d56280',
  'Soft Pink': '',
  'Heather Aqua': '',
  'Storm': '#847980',
  'Leaf': '',
  'Heather Orchid': '',
  'Berry': '',
  'Autumn': '',
  'Mustard': '',
  'Heather Sunset': '',
  'Heather Kelly': '',
  'Teal': '',
  'Jade Dome': '',
  'Daisy': '',
  'Peacock Blue': '',
  'Lilac': '',
};

/**
 * Get hex color for a Printify color name
 * Returns a default grey color if not found or not set
 */
export function getColorHex(colorName: string): string {
  return PRINTIFY_COLOR_MAP[colorName] || '#9CA3AF'; // Default to grey if not found
}
